apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: anyuid
users:
  - system:serviceaccount:dev-fayaaz:fayaaz-app-sa  # Placeholder; actual namespace will be set in overlays
