apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: anyuid
users:
  - system:serviceaccount:uat-sunaina:sunaina-sa  # Placeholder; actual namespace will be set in overlays
