apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fayaaz-app-rolebinding
  namespace: your-namespace  # Placeholder; actual namespace will be set in overlays
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sunaina-app-role
subjects:
  - kind: ServiceAccount
    name: sunaina-sa
    namespace: your-namespace  # Placeholder; actual namespace will be set in overlays
